CUDA_VISIBLE_DEVICES=0 python train.py \
--train_batch_size 64 \
--batch_split 1 \
--n_epochs 50 \
--lr 2e-4 \
--train_datasets datasets/triple/valid_both_original_final.txt \
--valid_datasets datasets/triple/valid_both_original_final.txt \
--test_datasets datasets/triple/valid_both_original_final.txt \
--train_datasets_cache datasets/triple/valid_both_original_final_cache \
--valid_datasets_cache datasets/triple/valid_both_original_final_cache \
--test_datasets_cache datasets/triple/valid_both_original_final_cache \
--vocab_path datasets/triple_valid_vocab \
--data_type triple \
--model_type seq2seq-rnn \
--pointer_gen \
--s2s_weight 1 \
--beam_size 1 \
--use_start_end \